
# ========================================
# API - ORDENS-SERVIÇO
# ========================================

### Buscar todas as OS's com (admin)
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=12&ano=2025

### Buscar todas as OS's com (admin) e filtra por codCliente
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025&codClienteFilter=120

### Buscar todas as OS's com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025&codClienteFilter=120&codRecursoFilter=122

### Buscar todas as OS's com (admin) e filtra por codCliente, codRecurso e status
GET http://localhost:3000/api/ordens-servico?isAdmin=true&mes=11&ano=2025&codClienteFilter=120&codRecursoFilter=122&statusFilter=finalizado

# ===============================================================================================================================================





# ========================================
# API - HRS-CONTRATADAS-HRS-EXECUTADAS
# ========================================

### Buscar todas as OS's com (admin)
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025

### Buscar todas as OS's com (admin) e filtra por codCliente
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025&codClienteFilter=120

### Buscar todas as OS's com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/hrs-contratadas-hrs-executadas?isAdmin=true&mes=11&ano=2025&codClienteFilter=120&codRecursoFilter=122


# ===============================================================================================================================================





# ========================================
# API - TABELA
# ========================================
### Buscar todos os dados da tabela com (admin)
GET http://localhost:3000/api/tabela?isAdmin=true&mes=12&ano=2025

### Buscar todos os dados da tabela com (admin) e filtra por codCliente
GET http://localhost:3000/api/tabela?isAdmin=true&mes=11&ano=2025&codClienteFilter=156

### Buscar todos os dados da tabela com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/tabela?isAdmin=true&mes=11&ano=2025&codClienteFilter=156&codRecursoFilter=122

# ===============================================================================================================================================





# ========================================
# API - CLIENTES
# ========================================
### Buscar todos os clientes com (admin)
GET http://localhost:3000/api/clientes?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - RECURSOS
# ========================================
### Buscar todos os recursos com (admin)
GET http://localhost:3000/api/recursos?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - STATUS
# ========================================
### Buscar todos os status com (admin)
GET http://localhost:3000/api/status?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================




# ========================================
# API - CHAMADOS
# ========================================
### Buscar todos os chamados de um determinado PERÍODO - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true



### Buscar todos os chamados de um CLIENTE específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&codClienteFilter=156



### Buscar todos os chamados com um RECURSO específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&codRecursoFilter=84



### Buscar todos os chamados com um STATUS específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&statusFilter=FINALIZADO



### Buscar todas as OS's vinculadas a um CHAMADO específico - ADMIN
GET http://localhost:3000//api/chamados/13513/os?isAdmin=true&mes=12&ano=2025





