# ========================================
# TOTAL DE CHAMADOS POR STATUS
# ========================================
# BUSCAR O TOTAL DE CHAMADOS POR STATUS
GET http://localhost:3000/api/dashboard/total-chamados-os?mes=01&ano=2026&codCliente=156
###





# ========================================
# HORAS CONTRATADAS X HORAS EXECUTADAS
# ========================================
# BUSCAR AS HORAS CONTRATADAS X HORAS EXECUTADAS
GET http://localhost:3000/api/dashboard/hrs-contratadas-hrs-executadas?&mes=01&ano=2026&codCliente=156
###





# ========================================
# MÉDIA DE HORAS POR CHAMADO
# ========================================
# BUSCAR A MÉDIA DE HORAS POR CHAMADO
GET http://localhost:3000/api/dashboard/media-hrs-chamado-tarefa?mes=01&ano=2026&codCliente=156
###






# ========================================
# API - CLIENTES
# ========================================
### Buscar todos os clientes com (admin)
GET http://localhost:3000/api/filtros/clientes?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - RECURSOS
# ========================================
### Buscar todos os recursos com (admin)
GET http://localhost:3000/api/filtros/recursos?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - STATUS
# ========================================
### Buscar todos os status com (admin)
GET http://localhost:3000/api/filtros/status?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================




# ========================================
# API - CHAMADOS
# ========================================
### Buscar todos os chamados de um determinado PERÍODO - ADMIN
GET http://localhost:3000/api/chamados?mes=01&ano=2026&isAdmin=true



### Teste: Não-Admin - Apenas ano (sem mês) - Chamados NÃO FINALIZADOS
GET http://localhost:3000/api/chamados?isAdmin=false&codCliente=156&ano=2025



### Teste: Não-Admin - Apenas ano (sem ano) - Chamados NÃO FINALIZADOS
GET http://localhost:3000/api/chamados?isAdmin=false&codCliente=156&mes=12



### Buscar todos os chamados de um CLIENTE específico - ADMIN
GET http://localhost:3000/api/chamados?mes=01&ano=2026&isAdmin=false&codCliente=156



### Buscar todos os chamados com um RECURSO específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&codRecursoFilter=84



### Buscar todos os chamados com um STATUS específico - ADMIN
GET http://localhost:3000/api/chamados?mes=01&ano=2026&isAdmin=false&codCliente=156&statusFilter=FINALIZADO



### Buscar todas as OS's vinculadas a um CHAMADO específico - ADMIN
GET http://localhost:3000/api/chamados/14123/os?isAdmin=true&mes=01&ano=2026














### Buscar histórico de 6 meses para cliente 123
GET http://localhost:3000/api/saldo-horas?codCliente=156&mes=12&ano=2025&isAdmin=true&mesesHistorico=6





