# ========================================
# API - HRS-CONTRATADAS-HRS x-EXECUTADAS
# ========================================

### Buscar todas as OS's - ADMIN
GET http://localhost:3000/api/cards-metricas/hrs-contratadas-hrs-executadas?isAdmin=true&mes=12&ano=2025

### Buscar todas as OS's com (admin) e filtra por codCliente
GET http://localhost:3000/api/cards-metricas/hrs-contratadas-hrs-executadas?isAdmin=true&mes=12&ano=2025&codClienteFilter=120

### Buscar todas as OS's com (admin) e filtra por codCliente e codRecurso
GET http://localhost:3000/api/cards-metricas/hrs-contratadas-hrs-executadas?isAdmin=true&mes=12&ano=2025&codClienteFilter=120&codRecursoFilter=122

# ===============================================================================================================================================





# ========================================
# API - CLIENTES
# ========================================
### Buscar todos os clientes com (admin)
GET http://localhost:3000/api/filtros/clientes?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - RECURSOS
# ========================================
### Buscar todos os recursos com (admin)
GET http://localhost:3000/api/filtros/recursos?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================





# ========================================
# API - STATUS
# ========================================
### Buscar todos os status com (admin)
GET http://localhost:3000/api/filtros/status?isAdmin=true&mes=11&ano=2025

# ===============================================================================================================================================




# ========================================
# API - CHAMADOS
# ========================================
### Buscar todos os chamados de um determinado PERÍODO - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true



### Buscar todos os chamados de um CLIENTE específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&codClienteFilter=158



### Buscar todos os chamados com um RECURSO específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&codRecursoFilter=84



### Buscar todos os chamados com um STATUS específico - ADMIN
GET http://localhost:3000/api/chamados?mes=12&ano=2025&isAdmin=true&statusFilter=FINALIZADO



### Buscar todas as OS's vinculadas a um CHAMADO específico - ADMIN
GET http://localhost:3000//api/chamados/13230/os?isAdmin=true&mes=12&ano=2025